#!/usr/bin/env bash
# File generated by pre-commit: https://pre-commit.com
# ID: 138fd403232d2ddd5efb44317e38bf03

# start templated
INSTALL_PYTHON=/usr/bin/python3
ARGS=(hook-impl --config=.pre-commit-config.yaml --hook-type=pre-commit)
# end templated


echo "|--------------------------------------------------------------|"
echo "                  git changes staged                            "

changed_files=$(git diff --name-only --ignore-submodules)

# Check if the output is empty
if [ -z "$changed_files" ]; then
  echo -e "\n Ready for commit."
else
  echo -e " Changes detected: $changed_files\n, please add [git add -A] them before committing."
  exit 1
fi

echo "|--------------------------------------------------------------|"
echo "                  running ROS linting                           "

echo " Running ament_cpplint"
ament_cpplint src/ include/
if [ $? -ne 0 ]; then
    echo "ament_cpplint failed"
    exit 1
fi

echo " Running ament_xmllint"
ament_xmllint package.xml
if [ $? -ne 0 ]; then
    echo "ament_xmllint failed"
    exit 1
fi

echo " Running ament_flake8"
ament_flake8 scripts/ dv_template_package/
if [ $? -ne 0 ]; then
    echo "ament_flake8 failed"
    exit 1
fi

echo " Running ament_pep257"
ament_pep257 scripts/ dv_template_package/
if [ $? -ne 0 ]; then
    echo "ament_pep257 failed"
    exit 1
fi

echo "|--------------------------------------------------------------|"

echo " Running Rosdep"
rosdep check --from-paths . --ignore-src --rosdistro=jazzy
if [ $? -ne 0 ]; then
    echo "rosdep failed"
    exit 1
fi

echo "|--------------------------------------------------------------|"
echo "                  running C++ linting                           "

var_cpp=$(git diff --name-only --diff-filter=AM HEAD -- '*.cpp' '*.h')
if [ -z "$var_cpp" ]; then
    echo "No changes in cpp files"
else
    echo "Changes detected in cpp files: $var_cpp"
    ./tidy-code.sh
    tidy_exit_code=$?

    if [ "$tidy_exit_code" -eq 2 ]; then
        echo "clang-tidy failed"
        exit 1
    fi
fi
echo "|--------------------------------------------------------------|"
echo "                          Interval                              "
echo "|--------------------------------------------------------------|"
echo -e "\n"
curl https://icanhazdadjoke.com/
echo -e "\n\n"
echo "|--------------------------------------------------------------|"
echo "                   Running pre-commit hooks                     "
echo "|--------------------------------------------------------------|"

HERE="$(cd "$(dirname "$0")" && pwd)"
ARGS+=(--hook-dir "$HERE" -- "$@")

if [ -x "$INSTALL_PYTHON" ]; then
    exec "$INSTALL_PYTHON" -mpre_commit "${ARGS[@]}"
elif command -v pre-commit > /dev/null; then
    exec pre-commit "${ARGS[@]}"
else
    echo 'pre-commit not found.  Did you forget to activate your virtualenv?' 1>&2
    exit 1
fi
